name: Build and Package JAR

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK 배포판
          java-version: '17' # 원하는 Java 버전

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Install Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.0

      - name: Build JAR
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar"
          target: "~"
          strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo yum update -y && sudo yum install -y java-21-amazon-corretto
            for pid in $(pgrep java); do
              if ps -p $pid -o args= | grep -q 'java -jar'; then
                echo "Java process with 'java -jar' found (PID: $pid). Terminating..."
                kill -9 $pid
              fi
            done
            echo 'DB_URL="jdbc:mysql://database-1.cj2acyakajuz.us-east-2.rds.amazonaws.com:3306/database-1?serverTimezone=Asia/Seoul"' | sudo tee -a /etc/environment
            echo 'DB_USER="admin"' | sudo tee -a /etc/environment
            echo 'DB_PASSWORD="Wlfkfsh2#"' | sudo tee -a /etc/environment
            source /etc/environment

            # Spring Boot 앱 실행
            DB_URL="$DB_URL" DB_USER="$DB_USER" DB_PASSWORD="$DB_PASSWORD" nohup java -jar ~/*.jar > ~/app.log 2>&1 &

