name: Build and Package JAR

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK 배포판
          java-version: '17' # 원하는 Java 버전

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Install Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.0

      - name: Build JAR
        run: ./gradlew bootJar

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo yum update -y && sudo yum install -y java-21-amazon-corretto
            for pid in $(pgrep java); do
              if ps -p $pid -o args= | grep -q 'java -jar'; then
                echo "Java process with 'java -jar' found (PID: $pid). Terminating..."
                kill -9 $pid
              fi
            done
            echo "nohup java -jar ~/*.jar > ~/app.log 2>&1 &" | at now
